### ISSUE TITLE
npm i 报错

### ISSUE THREAD

**Issue by Akameea** [XavierCHN/x-template#15]

**Comment by Akameea** [comment]
C:\Users\Birch\Desktop\work\couse>npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'matchme@0.1.6',
npm WARN EBADENGINE   required: { node: '>= 0.4.x < 0.9.0' },
npm WARN EBADENGINE   current: { node: 'v14.19.0', npm: '8.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'registry@0.3.0',
npm WARN EBADENGINE   required: { node: '>= 0.6.x < 0.9.0' },
npm WARN EBADENGINE   current: { node: 'v14.19.0', npm: '8.5.4' }
npm WARN EBADENGINE }

> postinstall
> node scripts/install.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../../build/Release/registry.node'
Require stack:
- C:\Users\Birch\Desktop\work\couse\node_modules\registry-js\dist\lib\registry.js
- C:\Users\Birch\Desktop\work\couse\node_modules\registry-js\dist\lib\index.js
- C:\Users\Birch\Desktop\work\couse\node_modules\steam-game-path\lib\cjs\index.js
- C:\Users\Birch\Desktop\work\couse\scripts\utils.js
- C:\Users\Birch\Desktop\work\couse\scripts\install.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (C:\Users\Birch\Desktop\work\couse\node_modules\registry-js\dist\lib\registry.js:5:7)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Birch\\Desktop\\work\\couse\\node_modules\\registry-js\\dist\\lib\\registry.js',
    'C:\\Users\\Birch\\Desktop\\work\\couse\\node_modules\\registry-js\\dist\\lib\\index.js',
    'C:\\Users\\Birch\\Desktop\\work\\couse\\node_modules\\steam-game-path\\lib\\cjs\\index.js',
    'C:\\Users\\Birch\\Desktop\\work\\couse\\scripts\\utils.js',
    'C:\\Users\\Birch\\Desktop\\work\\couse\\scripts\\install.js'
  ]
}
npm ERR! code 1
npm ERR! path C:\Users\Birch\Desktop\work\couse
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Birch\AppData\Local\npm-cache\_logs\2022-03-16T17_53_49_894Z-debug-0.log

**Comment by XavierCHN** [comment]
这个一般是npm环境配置的问题，建议移除`node_modules`文件夹后重新`npm i`
